Add job(a skeleton): run-migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -230,22 +230,35 @@ jobs:
             ansible-playbook -i inventory.txt configure-server.yml
       # Here's where you will add some code to rollback on failure      
 
-#   run-migrations:
-#     docker:
-#       # Docker image here that supports NodeJS
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Run migrations
-#           command: |
-#             # Your code here
-#             exit 1
-#       - run:
-#           name: Send migration results to memstash
-#           command: |
-#             # Your code here
-#             exit 1
-#      # Here's where you will add some code to rollback on failure      
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      - restore_cache:
+          keys: [backend-build--v1]  
+      - run:
+          name: Run migrations
+          working_directory: backend 
+          command: |
+            # Your code here
+            npm install
+            # npm run migrations > migrations.log
+            echo "has been XXXXXXexecuted successfully" >migrations.log
+            cat migrations.log
+      - run:
+          name: Send migration results to memstash
+          working_directory: backend 
+          command: |
+            # Your code here
+            RESULT=$(! grep -q "has been executed successfully" migrations.log; echo $?)
+            echo "RESULT=$RESULT"
+            curl -H "Content-Type: text/plain" -H "token: 271ce878-7b96-47f1-ae12-e706830ca519" \
+              --request PUT --data "$RESULT" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+            echo "CIRCLE_WORKFLOW_ID: $CIRCLE_WORKFLOW_ID"
+     # Here's where you will add some code to rollback on failure      
 
 #   deploy-frontend:
 #     docker:
@@ -365,8 +378,8 @@ workflows:
               # only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
       # - deploy-frontend:
       #     requires: [run-migrations]
       # - deploy-backend:
